
version: '1.0'

services:

  neel-shell:
    build:
      context: .
      dockerfile: ./dev_env/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-dev-env
    container_name: neel-shell
    volumes:
      - .:/project/neel
    command: |
      bash -c "
        neel-protogen &&
        npm run build &&
        cd ../ &&
        tail -f /dev/null
      "

  neel-processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp
    container_name: neel-processor
    volumes:
      - '.:/project/neel'
    depends_on:
      - neel-shell
    command: |
      bash -c "
        sleep 1 &&
        neel-tp -v \
          -C tcp://validator:4004
      "

  neel-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: neel-rest-api
    container_name: neel-rest-api
    volumes:
      - .:/project/neel
    ports:
      - '8040:8000'
    depends_on:
      - neel-shell
      - neel-ledger-sync
      - rethink
      - validator
    command: |
      bash -c "
        sleep 3 &&
        neel-rest-api \
          --host neel-rest-api \
          --db-host rethink \
          --validator tcp://validator:4004
      "
      
  neel-ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: neel-ledger-sync
    container_name: neel-ledger-sync
    volumes:
      - .:/project/neel
    depends_on:
      - neel-shell
      - rethink
      - validator
    command: |
      bash -c "
        sleep 1 &&
        neel-setup-db --host rethink &&
        neel-ledger-sync -vv \
          --db-host rethink \
          --validator tcp://validator:4004
      "

  rethink:
    image: rethinkdb:2.3
    container_name: rethink-db
    expose:
      - 8080
      - 28015
    ports:
      - '8042:8080'
      - '28042:28015'

  sawtooth-rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8043:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  sawtooth-shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: sawtooth-shell
    volumes:
      - '.:/project/neel'
    working_dir: /project/neel
    container_name: sawtooth-shell
    depends_on:
      - sawtooth-rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
        sawtooth keygen
        fi;
        tail -f /dev/null
      "
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4040:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
  poet-engine:
     image: hyperledger/sawtooth-poet-engine:1.0
     container_name: sawtooth-poet-engine
     volumes:
       - poet-shared:/poet-shared
     command: "bash -c \"\
         while [ ! -f /poet-shared/validator/keys/validator.priv ]; do sleep 1; done && \
         cp -a /poet-shared/validator/keys /etc/sawtooth && \
         poet-engine -C tcp://validator:5050 --component tcp://validator:4004 \
     \""
  
  poet-validator-registry-tp:
     image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
     container_name: sawtooth-poet-validator-registry-tp
     expose:
       - 4004
     command: poet-validator-registry-tp -C tcp://validator:4004
     environment:
       PYTHONPATH: /project/sawtooth-core/consensus/poet/common
     stop_signal: SIGKILL
